#ifndef __MEMORYMAP_H__
#define __MEMORYMAP_H__

#include "MainAppConfig.h"

//Dsp#4 memory processes define
#if ((MEMADDR_EXTRAM_START)&0xFFFF)
#define	MEMADDR_DSPINIT04_PCS00PAR00	(((MEMADDR_EXTRAM_START+0x10000)>>16)) // _LiveMic_Init
#define	MEMADDR_DSPINIT04_PCS00PAR00_NEXTBASE	((MEMADDR_EXTRAM_START+0x00017A80)) // next base address
#else
#define	MEMADDR_DSPINIT04_PCS00PAR00	(((MEMADDR_EXTRAM_START)>>16)) // _LiveMic_Init
#define	MEMADDR_DSPINIT04_PCS00PAR00_NEXTBASE	((MEMADDR_EXTRAM_START+0x00007A80)) // next base address
#endif

#endif //__MEMORYMAP_H__